### ISSUE TITLE
Could you please share the download script?

### ISSUE THREAD

**Issue by Becomebright** [th2l/EvokedExpr-TPF#1]
Hi, thanks for your great work. I find it hard to download all the videos. Could you please share your download script with me? THX again.

**Comment by th2l** [comment]
I just added notebook file that I used to download dataset. You need to install  pytube ([https://pytube.io/en/latest/user/install.html]()) in order to run it.

**Comment by Becomebright** [comment]
Thanks a lot! Your notebook is super helpful.
I've tried your script, but the downloaded videos do not have a suffix, e.g., '00DCWMfJIpc'. How do you ensure the downloaded videos are in the format of MP4?

**Comment by th2l** [comment]
I think there is an incompatible between the old version of pytube that I used and the lastest  pytube version. I updated the notebook to work with the lastest pytube version.
